/**
 * Vercelビルド用のダミーデータ
 * DB接続失敗時にフォールバックとして使用
 */
import { Consultant, Review } from '@prisma/client';

export type ConsultantWithReviews = Consultant & {
  reviews: Review[];
  consultations?: any[];
  user?: any;
};

export function getMockConsultants(): ConsultantWithReviews[] {
  return [
    {
      id: 'mock-1',
      email: 'miura@example.com',
      name: '三浦拓哉',
      headline: '元大手IT企業エンジニア → スタートアップCTO経験',
      profileSummary: 'IT・Web業界の転職支援を専門としています。直接エンジニア経験も活かし、技術的なキャリアパスから転職活動まで、リアルなアドバイスが強みです。',
      achievementsSummary: '大手IT企業からベンチャーまで、80名以上のエンジニア転職支援に実績。SNSでも毎日発信中。',
      thumbnailUrl: 'https://placehold.co/400x400?text=三浦拓哉',
      bio: 'IT・Web業界転職はお任せください！直接エンジニア経験も活かしリアルなアドバイスが強み。',
      specialties: 'IT,Web,エンジニア',
      experienceYears: 8,
      createdAt: new Date(),
      userId: null,
      snsFollowersTwitter: 3500,
      snsFollowersLinkedin: 800,
      snsFollowersInstagram: null,
      externalLinks: null,
      twitterHandle: 'miura_takuya',
      profileSourceRaw: null,
      twitterUrl: 'https://twitter.com/miura_takuya',
      linkedinUrl: 'https://linkedin.com/in/miura-takuya',
      schedulerUrl: 'https://timellex.example.com/miura-demo',
      timelexUrl: 'https://timellex.example.com/miura-demo',
      expertiseRoles: ['エンジニア', 'PdM', 'テックリード'],
      expertiseCompanyTypes: ['メガベンチャー', 'スタートアップ', '外資系'],
      ageRange: '30s_late',
      education: 'university',
      previousIndustry: 'it_internet',
      previousJobFunction: 'engineer',
      previousCompanies: ['Google', 'Microsoft'],
      specialtyIndustries: ['IT・インターネット', 'SaaS / スタートアップ'],
      specialtyJobFunctions: ['エンジニア', 'PdM / PM'],
      selfReportedCareerYears: 8,
      selfReportedTotalSupports: 80,
      selfReportedTotalPlacements: 60,
      selfReportedAverageAnnualIncome: null,
      totalSupportCount: 80,
      reviews: [
        {
          id: 'review-1',
          userId: null,
          consultantId: 'mock-1',
          consultationId: null,
          type: 'consultation',
          score: 5,
          comment: 'とても丁寧に相談に乗っていただきました。',
          meta: null,
          isApproved: true,
          createdAt: new Date(),
        },
      ],
    },
    {
      id: 'mock-2',
      email: 'kinoshita@example.com',
      name: '木下絵里',
      headline: '元大手メーカー営業 → スタートアップ営業責任者',
      profileSummary: '製造業や法人営業、メーカー転職の支援を専門としています。営業系への転職、管理職希望にも強い実績があります。',
      achievementsSummary: '営業系への転職、管理職希望にも強い。直近3年の内定率、業界平均を大きく上回っています。',
      thumbnailUrl: 'https://placehold.co/400x400?text=木下絵里',
      bio: '製造業や法人営業、メーカー転職なら必ず役立つ事例が語れます。',
      specialties: 'メーカー,営業,製造',
      experienceYears: 11,
      createdAt: new Date(),
      userId: null,
      snsFollowersTwitter: 1020,
      snsFollowersLinkedin: 1200,
      snsFollowersInstagram: 400,
      externalLinks: null,
      twitterHandle: 'kinoshita_eri',
      profileSourceRaw: null,
      twitterUrl: 'https://twitter.com/kinoshita_eri',
      linkedinUrl: 'https://linkedin.com/in/kinoshita-eri',
      schedulerUrl: 'https://timellex.example.com/kinoshita-demo',
      timelexUrl: 'https://timellex.example.com/kinoshita-demo',
      expertiseRoles: ['営業', 'マーケティング', 'セールス'],
      expertiseCompanyTypes: ['大企業', 'メーカー'],
      ageRange: '40s_plus',
      education: 'university',
      previousIndustry: 'manufacturing',
      previousJobFunction: 'sales',
      previousCompanies: ['Toyota', 'Sony'],
      specialtyIndustries: ['製造業', '金融'],
      specialtyJobFunctions: ['営業', 'マーケティング'],
      selfReportedCareerYears: 11,
      selfReportedTotalSupports: 120,
      selfReportedTotalPlacements: 90,
      selfReportedAverageAnnualIncome: null,
      totalSupportCount: 120,
      reviews: [
        {
          id: 'review-2',
          userId: null,
          consultantId: 'mock-2',
          consultationId: null,
          type: 'consultation',
          score: 5,
          comment: '営業転職のアドバイスが的確でした。',
          meta: null,
          isApproved: true,
          createdAt: new Date(),
        },
      ],
    },
    {
      id: 'mock-3',
      email: 'takahashi@example.com',
      name: '高橋悠馬',
      headline: '元外資系人事 → スタートアップ人事責任者',
      profileSummary: '管理部門やコーポレート職への転職に精通しています。働き方の疑問も一緒に整理しましょう。',
      achievementsSummary: '総務・人事採用・経理バックオフィスの支援実績が延べ50社以上。LinkedInでの社内改革記事が反響。',
      thumbnailUrl: 'https://placehold.co/400x400?text=高橋悠馬',
      bio: '管理部門やコーポレート職への転職に精通。働き方の疑問も一緒に整理しましょう。',
      specialties: 'コーポレート,人事,総務',
      experienceYears: 6,
      createdAt: new Date(),
      userId: null,
      snsFollowersTwitter: null,
      snsFollowersLinkedin: 2100,
      snsFollowersInstagram: null,
      externalLinks: null,
      twitterHandle: 'takahashi_yuma',
      profileSourceRaw: null,
      twitterUrl: null,
      linkedinUrl: 'https://linkedin.com/in/takahashi-yuma',
      schedulerUrl: 'https://timellex.example.com/takahashi-demo',
      timelexUrl: 'https://timellex.example.com/takahashi-demo',
      expertiseRoles: ['人事', '総務', '労務'],
      expertiseCompanyTypes: ['大企業', '外資系'],
      ageRange: '30s_early',
      education: 'university',
      previousIndustry: 'hr_consulting',
      previousJobFunction: 'hr',
      previousCompanies: ['Deloitte', 'PwC'],
      specialtyIndustries: ['人材・コンサル', '金融'],
      specialtyJobFunctions: ['人事', '経理・財務'],
      selfReportedCareerYears: 6,
      selfReportedTotalSupports: 50,
      selfReportedTotalPlacements: 40,
      selfReportedAverageAnnualIncome: null,
      totalSupportCount: 50,
      reviews: [],
    },
    {
      id: 'mock-4',
      email: 'suzuki@example.com',
      name: '鈴木葵',
      headline: '元大手企業人事 → ワーママ転職支援専門',
      profileSummary: '子育て・ケアとキャリア形成の両立支援が得意です。女性の転職や両立も親身に相談します。',
      achievementsSummary: 'ワーママ転職の支援・カウンセリング実績多数。事務・時短勤務など多様な働き方提案を発信しています。',
      thumbnailUrl: 'https://placehold.co/400x400?text=鈴木葵',
      bio: '子育て・ケアとキャリア形成の両立支援が得意です。女性の転職や両立も親身に相談。',
      specialties: '両立支援,事務,女性転職',
      experienceYears: 13,
      createdAt: new Date(),
      userId: null,
      snsFollowersTwitter: 480,
      snsFollowersLinkedin: null,
      snsFollowersInstagram: 1220,
      externalLinks: null,
      twitterHandle: 'suzuki_aoi',
      profileSourceRaw: null,
      twitterUrl: 'https://twitter.com/suzuki_aoi',
      linkedinUrl: null,
      schedulerUrl: 'https://timellex.example.com/suzuki-demo',
      timelexUrl: 'https://timellex.example.com/suzuki-demo',
      expertiseRoles: ['事務', 'コーポレート', '両立支援'],
      expertiseCompanyTypes: ['大企業', 'スタートアップ'],
      ageRange: '30s_late',
      education: 'vocational',
      previousIndustry: 'other_service',
      previousJobFunction: 'hr',
      previousCompanies: ['Recruit', 'Persol'],
      specialtyIndustries: ['その他サービス'],
      specialtyJobFunctions: ['事務', '人事'],
      selfReportedCareerYears: 13,
      selfReportedTotalSupports: 90,
      selfReportedTotalPlacements: 70,
      selfReportedAverageAnnualIncome: null,
      totalSupportCount: 90,
      reviews: [],
    },
  ] as unknown as ConsultantWithReviews[];
}

export function getMockConsultant(id: string): ConsultantWithReviews | null {
  const consultants = getMockConsultants();
  return consultants.find(c => c.id === id) || null;
}

